classifier/urls.py
from django.urls import path

from . import views

app_name = 'classifier'
urlpatterns = [
    path('', views.index, name='predict'),
    path('process_file/', views.process_file, name='process_file'),
]

spam_detection/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('classifier.urls'))
]

classifier/models.py
from django.db import models


class Message(models.Model):
    text = models.TextField()
    label = models.IntegerField()

    def __str__(self):
        return f'{self.text}: {self.text}'

classifier/forms.py
from django import forms


class UploadFileForm(forms.Form):
    #title = forms.CharField(max_length=50)
    file = forms.FileField()

classifier/views.py
import pickle

import pandas as pd
from django.conf import settings
from django.shortcuts import render, redirect

from classifier.forms import UploadFileForm

app_path = settings.BASE_DIR / 'classifier'
estimator_path = app_path / 'estimator.pkl'

with open(estimator_path, 'rb') as f:
    classifier = pickle.load(f)


def index(request):
    if request.method == 'GET':
        return render(request, 'classifier/index.html')
    elif request.method == 'POST':
        sms = request.POST['input']
        prediction = classifier.predict([sms])
        predicted_label = 'Ham' if prediction[0] == 0 else 'Spam'
        estimated_probabilities = classifier.predict_proba([sms])[0]
        probability = f'{max(estimated_probabilities):.2%}'
        context = {'prediction': predicted_label,
                   'probability': probability,
                   'sms': sms}
        return render(request, 'classifier/index.html', context)


def process_file(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            file = request.FILES['file']
            if file.name.endswith('.csv') or file.name.endswith('.xlsx'):
                df = predict_csv(file)
                result_path = settings.BASE_DIR / 'classifier' / 'results' / f'{file.name[:-4]}_result.csv'
                df.to_csv(result_path, index=False)
                print(result_path.resolve())
                return download_file(request, result_path)
            return redirect('classifier:process_file')
        else:
            print('invalid')
    else:
        form = UploadFileForm()
    return render(request, 'classifier/uploading_files.html', {'form': form})


def predict_csv(file):
    """This function takes in a csv file and predict the labels for each row and return a new csv file with the result"""
    df = pd.read_csv(file, header=None, names=['text'])
    df['predicted_label'] = classifier.predict(df['text'])
    df['predicted_label'].replace({0: 'Ham', 1: 'Spam'}, inplace=True)
    df['probability_spam'] = classifier.predict_proba(df['text'])[:, 1]
    print(classifier.predict_proba(df['text'])[:, 1])
    print(df.head())

    print('hadaf')
    return df


from django.http import FileResponse


def download_file(request, file_path):
    response = FileResponse(open(file_path, 'rb'), content_type='text/plain')
    response['Content-Disposition'] = f'attachment; filename="{file_path.name}"'
    return response

classifier/templates/classifier/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'classifier/style.css' %}">
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="container">
    <h2>Making predictions</h2>

    Please enter your SMS below and click the Predict button.

    <form action="{% url 'classifier:predict' %}" method="post">
        {% csrf_token %}
        <input type="text" name="input" placeholder="Enter your SMS">
        <input type="submit" value="Predict">
    </form>

    {% if prediction %}
        <div class="prediction">
            <p>The SMS is:</p>
            <blockquote>{{ sms }}.</blockquote>
            <p>The predicted label is <b>{{ prediction }}</b>.</p>
            <p>The model is <b>{{ probability }}</b> sure.</p>
        </div>
    {% endif %}
</div>
</body>
</html>

classifier/templates/classifier/uploading_files.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>If you prefer, you can also upload a file with several sms. Only csv and xlsx (excel) are allowed</p>
<form action="{% url 'classifier:process_file' %}"  method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.file }}
    <button type="submit">Upload</button>
</form>

{% if result_file %}
    <p>Your file is ready!</p>
    <a href="{{ result_file }}" download="{{ result_file }}">Download result file</a>
{% endif %}
</body>
</html>